Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [76]:
import numpy as np
import random as random
n = random.randint(0, 20)
b = []
for i in range(n):
    n -= 1
    b.append(n)

a = np.array(b)
a

array([7, 6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [133]:
n = random.randint(0, 20)
a = np.zeros((n, n))
i, j = np.indices(a.shape)
a
for i in range(n):
    n -= 1
    a[i==j] = n

a = np.diag(np.diag(a))
a

array([[9., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 8., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 7., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 6., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 5., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 4., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 3., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 2., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [134]:
np.sum(a)

45.0

Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [135]:
M = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
V = np.array([4, 12, -3])
np.linalg.solve(M, V)

array([ 0.46666667,  3.84444444, -5.55555556])